export const banks = {
  items: [
    {
      id: '1',
      no: 1,
      code: 160,
      abbreviation: '',
      account: '160-464572-90',
      name: 'Banca Intesa A.D.- Beograd',
      address: 'Milentija Popovića 7b, Beograd',
      isActive: true,
    },
    {
      id: '2',
      no: 2,
      code: 370,
      abbreviation: '3Bank',
      account: '',
      name: '3 BANKA a.d. Novi Sad',
      address: 'Bulevar oslobođenja 2a, Novi Sad',
      isActive: false,
    },
    {
      id: '3',
      no: 3,
      code: 165,
      abbreviation: 'Addiko',
      account: '',
      name: 'Addiko Bank AD Beograd',
      address: 'Bulevar Mihajla Pupina 6, Beograd',
      isActive: false,
    },
    {
      id: '4',
      no: 4,
      code: 145,
      abbreviation: 'Adriatic',
      account: '',
      name: 'Adriatic Bank akcionarsko društvo Beograd',
      address: 'Dalmatinska 22, Beograd',
      isActive: false,
    },
    {
      id: '5',
      no: 5,
      code: 105,
      abbreviation: 'AIK',
      account: '',
      name: 'Agroindustrijska komercijalna banka AIK banka akcionarsko društvo, Beograd',
      address: 'Bulevar Mihaila Pupina 115đ, Beograd (Novi Beograd)',
      isActive: false,
    },
    {
      id: '6',
      no: 6,
      code: 190,
      abbreviation: 'ALTA',
      account: '',
      name: 'ALTA BANKA A.D. BEOGRAD',
      address: 'Bulevar Zorana Đindića 121, Beograd',
      isActive: false,
    },
    {
      id: '7',
      no: 7,
      code: 375,
      abbreviation: 'API Banka',
      account: '',
      name: 'API Bank akcionarsko društvo Beograd',
      address: 'Bul.Vojvode Bojovića 6-8, Beograd',
      isActive: false,
    },
    {
      id: '8',
      no: 8,
      code: 385,
      abbreviation: '',
      account: '',
      name: 'Bank of China Srbija akcionarsko društvo Beograd - Novi Beograd',
      address: 'Bulevar Zorana Đinđića 2a, Beograd (Novi Beograd)',
      isActive: false,
    },
    {
      id: '9',
      no: 9,
      code: 200,
      abbreviation: 'Poštanska štedionica',
      account: '',
      name: 'Banka Poštanska štedionica A.D.- Beograd',
      address: 'Kraljice Marije 3, Beograd',
      isActive: false,
    },
    {
      id: '10',
      no: 10,
      code: 340,
      abbreviation: 'Erste',
      account: '',
      name: 'Erste Bank A.D.- Novi Sad',
      address: 'Bulevar oslobođenja 5, Novi Sad',
      isActive: false,
    },
  ],
  meta: {
    totalItems: 10,
    totalPages: 1,
    currentPage: 1,
    itemCount: 10,
    itemsPerPage: 10,
  },
};
