export const bills = {
  items: [
    {
      id: '1',
      no: 1,
      documentName: 'Bill type A',
      deliver: 'Deliver A',
      date: '2024-01-30',
      currencyDate: '2024-01-30',
      supplier: {
        value: '1',
        label: 'Milan Jovanović',
      },
      status: 'Paid',
      nbsExchangeRate: 117.5,
      baseAmount: 1000,
      taxAmount: 200,
      totalAmount: 1200,
      description: 'This is a sample bill description for Bill type A.',
    },
    {
      id: '2',
      no: 2,
      documentName: 'Bill type B',
      deliver: 'Deliver B',
      date: '2024-02-15',
      currencyDate: '2024-02-15',
      supplier: {
        value: '2',
        label: 'Ana Petrović',
      },
      status: 'Unpaid',
      nbsExchangeRate: 117.5,
      baseAmount: 2000,
      taxAmount: 400,
      totalAmount: 2400,
    },
    {
      id: '3',
      no: 3,
      documentName: 'Bill type C',
      deliver: 'Deliver C',
      date: '2024-03-10',
      currencyDate: '2024-03-10',
      supplier: {
        value: '3',
        label: 'Marko Marković',
      },
      status: 'Pending',
      nbsExchangeRate: 117.5,
      baseAmount: 1500,
      taxAmount: 300,
      totalAmount: 1800,
    },
    {
      id: '4',
      no: 4,
      documentName: 'Bill type D',
      deliver: 'Deliver D',
      date: '2024-04-05',
      currencyDate: '2024-04-05',
      supplier: {
        value: '4',
        label: 'Jelena Jovanović',
      },
      status: 'Paid',
      nbsExchangeRate: 117.5,
      baseAmount: 2500,
      taxAmount: 500,
      totalAmount: 3000,
    },
    {
      id: '5',
      no: 5,
      documentName: 'Bill type E',
      deliver: 'Deliver E',
      date: '2024-05-20',
      currencyDate: '2024-05-20',
      supplier: {
        value: '5',
        label: 'Petar Petrović',
      },
      status: 'Unpaid',
      nbsExchangeRate: 117.5,
      baseAmount: 3000,
      taxAmount: 600,
      totalAmount: 3600,
    },
  ],
  meta: {
    currentPage: 1,
    itemsPerPage: 10,
    totalItems: 4,
    totalPages: 1,
  },
};
