export const compensationDocuments = {
  items: [
    {
      id: '1',
      no: 1,
      partner: 'Partner 1',
      invoice: 'INV-001',
      bill: 'BILL-001',
      amount: 1000,
      compensated: true,
      compensationId: '1',
    },
    {
      id: '2',
      no: 2,
      partner: 'Partner 2',
      invoice: 'INV-002',
      bill: 'BILL-002',
      amount: 2000,
      compensated: false,
      compensationId: '1',
    },
    {
      id: '3',
      no: 3,
      partner: 'Partner 3',
      invoice: 'INV-003',
      bill: 'BILL-003',
      amount: 1500,
      compensated: true,
      compensationId: '2',
    },
    {
      id: '4',
      no: 4,
      partner: 'Partner 4',
      invoice: 'INV-004',
      bill: 'BILL-004',
      amount: 3000,
      compensated: false,
      compensationId: '2',
    },
    {
      id: '5',
      no: 5,
      partner: 'Partner 5',
      invoice: 'INV-005',
      bill: 'BILL-005',
      amount: 2500,
      compensated: true,
      compensationId: '3',
    },
  ],
  meta: {
    totalItems: 5,
    totalPages: 1,
    currentPage: 1,
    itemCount: 5,
    itemsPerPage: 10,
  },
};
