export const compensations = {
  items: [
    {
      id: '1',
      no: 1,
      document: 'Document 1',
      compensationType: 'Exit',
      client: 'Client 1',
      description: 'Description 1',
      date: '2021-01-01',
      currencyDate: '2021-01-01',
      baseAmount: 100,
      vat: 20,
      total: 120,
      nbsExchangeRate: 100,
    },
    {
      id: '2',
      no: 2,
      document: 'Document 2',
      compensationType: 'Entry',
      client: 'Client 2',
      description: 'Description 2',
      date: '2021-02-02',
      currencyDate: '2021-02-02',
      baseAmount: 200,
      vat: 40,
      total: 240,
      nbsExchangeRate: 200,
    },
    {
      id: '3',
      no: 3,
      document: 'Document 3',
      compensationType: 'Exit',
      client: 'Client 3',
      description: 'Description 3',
      date: '2021-03-03',
      currencyDate: '2021-03-03',
      baseAmount: 300,
      vat: 60,
      total: 360,
      nbsExchangeRate: 300,
    },
    {
      id: '4',
      no: 4,
      document: 'Document 4',
      compensationType: 'Entry',
      client: 'Client 4',
      description: 'Description 4',
      date: '2021-04-04',
      currencyDate: '2021-04-04',
      baseAmount: 400,
      vat: 80,
      total: 480,
      nbsExchangeRate: 400,
    },
    {
      id: '5',
      no: 5,
      document: 'Document 5',
      compensationType: 'Exit',
      client: 'Client 5',
      description: 'Description 5',
      date: '2021-05-05',
      currencyDate: '2021-05-05',
      baseAmount: 500,
      vat: 100,
      total: 600,
      nbsExchangeRate: 500,
    },
  ],
  meta: {
    totalItems: 10,
    totalPages: 1,
    currentPage: 1,
    itemCount: 10,
    itemsPerPage: 10,
  },
};
