export const containers = {
  items: [
    {
      id: '1',
      no: 1,
      dropOffDate: '2025-01-28',
      pickUpDate: '2025-01-30',
      client: 'Logistics Solutions Inc.',
      carrier: 'OceanX Shipping Co.',
      droppedBy: 'John Doe',
      pickedUpBy: 'Jane Smith',
      containerNumber: 'CONT1234567',
      description: 'Electronics shipment',
      waitingTime: 2,
      price: 1500.0,
    },
    {
      id: '2',
      no: 2,
      dropOffDate: '2025-01-20',
      pickUpDate: '2025-01-25',
      client: 'Global Freight Corp.',
      carrier: 'Seaway Transport Ltd.',
      droppedBy: 'Michael Johnson',
      pickedUpBy: 'Sarah Brown',
      containerNumber: 'CONT7654321',
      description: 'Furniture and decor',
      waitingTime: 5,
      price: 2400.0,
    },
    {
      id: '3',
      no: 3,
      dropOffDate: '2025-01-10',
      pickUpDate: '2025-01-12',
      client: 'Prime Shipping Partners',
      carrier: 'Blue Ocean Lines',
      droppedBy: 'Emily Carter',
      pickedUpBy: 'Robert White',
      containerNumber: 'CONT3456789',
      description: 'Frozen food products',
      waitingTime: 2,
      price: 1800.0,
    },
    {
      id: '4',
      no: 4,
      dropOffDate: '2025-01-15',
      pickUpDate: '2025-01-18',
      client: 'CargoFlow Ltd.',
      carrier: 'Maritime Movers',
      droppedBy: 'Laura Green',
      pickedUpBy: 'James Black',
      containerNumber: 'CONT9876543',
      description: 'Construction materials',
      waitingTime: 3,
      price: 2200.0,
    },
    {
      id: '5',
      no: 5,
      dropOffDate: '2025-01-05',
      pickUpDate: '2025-01-08',
      client: 'NextPort Logistics',
      carrier: 'Atlantic Shipments',
      droppedBy: 'Oliver King',
      pickedUpBy: 'Sophia Harris',
      containerNumber: 'CONT1928374',
      description: 'Clothing and textiles',
      waitingTime: 3,
      price: 1700.0,
    },
  ],
  meta: {
    totalItems: 10,
    totalPages: 1,
    currentPage: 1,
    itemCount: 10,
    itemsPerPage: 10,
  },
};
