export const employees = {
  items: [
    {
      id: '1',
      no: 1,
      firstName: 'Mica',
      lastName: 'Micic',
      nickname: 'Mica',
      isAssociate: true,
      dateOfBirth: '1990-01-01',
      idCardNumber: '1234567890123',
      nationalId: '1234567890123',
      address: '123 Main St, Belgrade',
      domesticTourPercentage: 50,
      internationalTourPercentage: 50,
      salary: 50000,
      salaryAccount: '123456789012345678',
      fuel: 'Petrol',
      religiousHoliday: 'Christmas',
      isActiveEmployee: true,
      isActiveForPayroll: true,
      gender: 1,
      email: 'mica@micic.com',
      isPartner: false,
      employeeRole: 'Dispečer',
    },
    {
      id: '2',
      no: 2,
      firstName: 'Jovan',
      lastName: 'Jovanovic',
      email: 'jovan@jovanovic.com',
      isPartner: true,
      employeeRole: 'Vozač',
    },
    {
      id: '3',
      no: 3,
      firstName: 'Petar',
      lastName: 'Peric',
      email: 'petar@peric.com',
      isPartner: false,
      employeeRole: 'Referent',
    },
  ],
  meta: {
    totalItems: 3,
    totalPages: 1,
    currentPage: 1,
    itemCount: 3,
    itemsPerPage: 10,
  },
};
