export const financeDesk = {
  items: [
    {
      id: '1',
      no: 1,
      date: '2024-01-30',
      employee: 'Milan Jovanović',
      description: 'Gotovinski polog',
      dissolution: 5000,
    },
    {
      id: '2',
      no: 2,
      serialNumber: '002',
      date: '2024-01-29',
      employee: 'Ana Petrović',
      description: 'Isplata zarade',
      debt: 20000,
    },
    {
      id: '3',
      no: 3,
      serialNumber: '003',
      date: '2024-01-28',
      employee: 'Marko Ilić',
      description: 'Kupovina materijala',
      debt: 5000,
    },
    {
      id: '4',
      no: 4,
      serialNumber: '004',
      date: '2024-01-27',
      employee: 'Jelena Jovanović',
      description: 'Kupovina materijala',
      dissolution: 7000,
    },
    {
      id: '5',
      no: 5,
      serialNumber: '005',
      date: '2024-01-26',
      employee: 'Nikola Jovanović',
      description: 'Kupovina materijala',
      dissolution: 7000,
    },
    {
      id: '6',
      no: 6,
      serialNumber: '006',
      date: '2024-01-25',
      employee: 'Milan Jovanović',
      description: 'Kupovina materijala',
      debt: 5000,
    },
    {
      id: '7',
      no: 7,
      serialNumber: '007',
      date: '2024-01-24',
      employee: 'Ana Petrović',
      description: 'Kupovina materijala',
      dissolution: 7000,
    },
    {
      id: '8',
      no: 8,
      serialNumber: '008',
      date: '2024-01-23',
      employee: 'Marko Ilić',
      description: 'Kupovina materijala',
      debt: 5000,
    },
    {
      id: '9',
      no: 9,
      serialNumber: '009',
      date: '2024-01-22',
      employee: 'Jelena Jovanović',
      description: 'Kupovina materijala',
      dissolution: 7000,
    },
    {
      id: '10',
      no: 10,
      serialNumber: '010',
      date: '2024-01-21',
      employee: 'Nikola Jovanović',
      description: 'Kupovina materijala',
      debt: 5000,
    },
  ],
  meta: {
    totalItems: 10,
    totalPages: 1,
    currentPage: 1,
    itemCount: 10,
    itemsPerPage: 10,
  },
};
