export const invoices = {
  items: [
    {
      id: "1",
      no: 1,
      international: true,
      documentNumber: "0001/25",
      client: {
        value: "1",
        label: "Milan Jovanović",
      },
      transactionDate: "2024-01-30",
      issueDate: "2024-01-30",
      currencyDate: "2024-01-30",
      nbsExchangeRate: 117.5,
      bankAccount: {
        value: "1",
        label: "Raiffeisen Banka",
      },
      description: "Usluge",
      note: "Usluge",
    },
    {
      id: "2",
      no: 2,
      international: false,
      documentNumber: "0002/25",
      client: {
        value: "2",
        label: "Ana Petrović",
      },
      transactionDate: "2024-02-15",
      issueDate: "2024-02-15",
      currencyDate: "2024-02-15",
      nbsExchangeRate: 117.5,
      bankAccount: {
        value: "2",
        label: "Banca Intesa",
      },
      description: "Usluge",
      note: "Usluge",
    },
    {
      id: "3",
      no: 3,
      international: true,
      documentNumber: "0003/25",
      client: {
        value: "3",
        label: "Marko Marković",
      },
      transactionDate: "2024-03-10",
      issueDate: "2024-03-10",
      currencyDate: "2024-03-10",
      nbsExchangeRate: 117.5,
      bankAccount: {
        value: "3",
        label: "Vojvođanska Banka",
      },
      description: "Usluge",
      note: "Usluge",
    },
    {
      id: "4",
      no: 4,
      international: false,
      documentNumber: "0004/25",
      client: {
        value: "4",
        label: "Jelena Jovanović",
      },
      transactionDate: "2024-04-05",
      issueDate: "2024-04-05",
      currencyDate: "2024-04-05",
      nbsExchangeRate: 117.5,
      bankAccount: {
        value: "4",
        label: "OTP Banka",
      },
      description: "Usluge",
      note: "Usluge",
    },
  ],
  meta: {
    currentPage: 1,
    itemsPerPage: 10,
    totalItems: 4,
    totalPages: 1,
  },
};
