export const suppliers = {
  items: [
    {
      id: '1',
      no: 1,
      pib: '123456789',
      name: 'Supplier 1',
      email: 'supplier1@supplier.com',
      address: 'Address 1',
      ptt: '11000',
      city: 'Beograd',
      state: 'Srbija',
      municipality: 'Beograd',
      companyAccounts: ['270-1123-00', '270-1124-00'],
      shortName: 'S1',
      supplierType: 1,
    },
    {
      id: '2',
      no: 2,
      pib: '223456789',
      name: 'Supplier 2',
      email: 'supplier2@supplier.com',
      address: 'Address 2',
      ptt: '18000',
      city: 'Niš',
      state: 'Srbija',
      phoneNumber: '123456789',
    },
    {
      id: '3',
      no: 3,
      pib: '123456779',
      name: 'Supplier 3',
      email: 'supplier3@supplier.com',
      address: 'Address 3',
      ptt: '17000',
      city: 'Vranje',
      state: 'Srbija',
    },
    {
      id: '4',
      no: 4,
      pib: '143456779',
      name: 'Supplier 4',
      email: 'supplier4@supplier.com',
      address: 'Address 4',
      ptt: '17000',
      city: 'Vranje',
      state: 'Srbija',
    },
    {
      id: '5',
      no: 5,
      pib: '145456779',
      name: 'Supplier 5',
      email: 'supplier5@supplier.com',
      address: 'Address 5',
      ptt: '18000',
      city: 'Niš',
      state: 'Srbija',
    },
  ],
  meta: {
    totalItems: 10,
    totalPages: 1,
    currentPage: 1,
    itemCount: 10,
    itemsPerPage: 10,
  },
};
