export enum TourStatus {
  Open = 'open',
  Started = 'started',
  Completed = 'completed',
  Canceled = 'canceled',
}

export enum DistributionType {
  Partner = 'partner',
  Internal = 'internal',
}

export enum inoTourType {
  Import = 'import',
  Export = 'export',
}

export const tours = {
  items: [
    {
      tours: [
        {
          id: '1',
          no: 1,
          status: TourStatus.Open,
          tourNumber: '3021/12',
          date: '2025-01-13',
          inoTour: false,
          invoiceNumber: 'INV-2025-001',
          driver: { value: '123', label: 'Milan Jovanovic' },
          vehicle: 'Mercedes Sprinter',
          client: 'Novi Sad Transport',
          description: 'Delivery of goods to client',
          expenses: 450.75,
          amount: 3200.5,
          documentation: 'All documents submitted',
          distributionType: DistributionType.Internal,
          note: 'Delivery completed on time.',
          invoiceAmountInOriginalCurrency: 3200.5,
          amountInOriginalCurrency: 450.75,
          tourLength: 380,
          isDocumentBrought: true,
        },
        {
          id: '2',
          no: 2,
          status: TourStatus.Started,
          tourNumber: '3050',
          date: '2025-01-14',
          inoTour: true,
          inoTourType: inoTourType.Export,
          invoiceNumber: 'INV-2025-002',
          client: 'Beograd Express',
          description: 'International delivery to Hungary',
          expenses: 890.0,
          amount: 4200.0,
          documentation: 'Pending driver submission',
          distributionType: DistributionType.Partner,
          partner: 'Hungarian Transport',
          note: 'Driver will submit documentation upon return.',
          invoiceAmountInOriginalCurrency: 4200.0,
          amountInOriginalCurrency: 890.0,
          tourLength: 620,
          isDocumentBrought: false,
        },
        {
          id: '3',
          no: 3,
          status: TourStatus.Completed,
          tourNumber: '3085',
          date: '2025-01-16',
          inoTour: false,
          invoiceNumber: 'INV-2025-003',
          driver: 'Ivan Markovic',
          vehicle: 'Volkswagen Crafter',
          client: 'Belgrade Logistics',
          description: 'Local distribution of electronic goods',
          expenses: 230.0,
          amount: 2800.0,
          documentation: 'All documents submitted',
          distributionType: DistributionType.Internal,
          note: 'Goods delivered successfully.',
          invoiceAmountInOriginalCurrency: 2800.0,
          amountInOriginalCurrency: 230.0,
          tourLength: 150,
          isDocumentBrought: true,
        },
        {
          id: '4',
          no: 4,
          status: TourStatus.Canceled,
          tourNumber: '3102',
          date: '2025-01-18',
          inoTour: true,
          inoTourType: inoTourType.Import,
          invoiceNumber: 'INV-2025-004',
          client: 'Vienna Cargo',
          description: 'Cancelled import from Austria',
          expenses: 0.0,
          amount: 0.0,
          documentation: 'No documents submitted',
          distributionType: DistributionType.Partner,
          partner: 'Austrian Freight',
          note: 'Tour canceled due to unforeseen circumstances.',
          invoiceAmountInOriginalCurrency: 0.0,
          amountInOriginalCurrency: 0.0,
          tourLength: 0,
          isDocumentBrought: false,
        },
        {
          id: '5',
          no: 5,
          status: TourStatus.Open,
          tourNumber: '3150',
          date: '2025-01-20',
          inoTour: false,
          invoiceNumber: 'INV-2025-005',
          driver: 'Zoran Kovacevic',
          vehicle: 'Fiat Ducato',
          client: 'Cargo Pro',
          description: 'Ongoing tour within Serbia',
          expenses: 300.0,
          amount: 3500.0,
          documentation: 'Pending driver submission',
          distributionType: DistributionType.Internal,
          note: 'Driver still on the route.',
          invoiceAmountInOriginalCurrency: 3500.0,
          amountInOriginalCurrency: 300.0,
          tourLength: 280,
          isDocumentBrought: false,
        },
      ],
    },
  ],
  meta: {
    totalItems: 10,
    totalPages: 1,
    currentPage: 1,
    itemCount: 10,
    itemsPerPage: 10,
  },
};
